### ISSUE TITLE
Assignment instead of comparison

### ISSUE THREAD

**Issue by DanielMSchmidt** [juddey/ignite-detox#2]
Hey there,

while looking through the code I found this line: `os.platform = 'darwin'` in https://github.com/juddey/ignite-detox/blob/master/plugin.js#L29.

Wouldn't this set the value of `os.platform` instead of checking it?

**Comment by juddey** [comment]
Oh, yes it would! Good catch.
Sorry about the wait on reply. I forgot to watch the repo! :man_facepalming:
